name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up SSH agent for deployment
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Сборка Docker образа
      - name: Build Docker image
        run: docker build -t safronovt/telegram-bot-chatgpt .
        env:
          TELEGRAM_BOT_TOKEN: 6080665930:AAFe_YiHBQ-YrlVedoK9ONGyDM5Ncjft2_4
          TELEGRAM_BOT_USERNAME: 123
          TELEGRAM_PERSON_ID: 123
          ADMIN_TELEGRAM_PERSON_ID: 123
          CHAT_GPT_TOKEN: 123

      # Публикация образа в Docker репозиторий
      - name: Push Docker image to registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push safronovt/telegram-bot-chatgpt

      # Развертывание на сервере
      - name: Deploy to server
        run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
               # Получить ID старого образа
               OLD_IMAGE_ID=$(docker images -q safronovt/telegram-bot-chatgpt:latest)
          
               # Скачать последнюю версию образа
               docker pull safronovt/telegram-bot-chatgpt:latest
          
               if [ $(docker ps -a -q -f name=telegram-bot-chatgpt) ]; then
                  docker stop telegram-bot-chatgpt
                  docker rm telegram-bot-chatgpt
               fi
          
               docker run --name telegram-bot-chatgpt -d safronovt/telegram-bot-chatgpt:latest
          
               # Удалить старый образ, если он существует и отличается от нового
               if [ -n "$OLD_IMAGE_ID" ] && [ "$OLD_IMAGE_ID" != "$(docker images -q safronovt/telegram-bot-chatgpt:latest)" ]; then
                 docker rmi $OLD_IMAGE_ID
               fi           
            EOF

